### ISSUE TITLE
At.js replace all text before caret in contenteditable if there's no whitespace after the first inserted tag

### ISSUE THREAD

**Issue by night-crawler** [ichord/At.js#245]
Hi!

I'm using `At.js` to insert images. When there's no whitespace after the first inserted image, inserting a new tag replaces all text from newline with a new image.

Example:
`[@img_inserted_here]some_text_without_spaces`

Then I'm adding a new image from the selector:
`[@img_inserted_here]some_text_without_spaces[@new_img]`

And the result after item was selected is:
`[@new_img]`

When I wrap inserting `img` with `<span contenteditable=false/>` it works perfect.

    at_config =
        at: '::',
        displayTpl: """<li>#{img_tpl}</li>""",
        insertTpl: """<span contenteditable=false>#{img_tpl}</span>""",
        startWithSpace: false,
        limit: 10000,
        searchKey: 'data-sequence'

How to do the same without `contenteditable` wrapper? Because sometimes cursor behaviour around `contenteditable==false` looks strange.

Thanks.

**Comment by ichord** [comment]
Since At.js will wrap all inserted element with a `div.atwho-inserted`, you can unwrap the image which is inside it. The `div.atwho-inserted` is a helper wrapper of At.js;

bind `inserted.atwho` events and unwrap `.atwho-inserted img` the element:

```javascript
    $('#editable').on('inserted.atwho', function(e){
      $(this).find('.atwho-inserted img').first().unwrap();
    });
```

At.js can't do it automatically, for there may be not just img inside.
