### ISSUE TITLE
Will At.js supports Rich text type of editors ?

### ISSUE THREAD

**Issue by signalarun** [ichord/At.js#270]

**Comment by ichord** [comment]
what kind of rich text type of editors, give me some examples.

**Comment by ichord** [comment]
close for no more information.

**Comment by elkuku** [comment]
I'm adding my request here since the title somewhat "fits" my needs.

I guess the OP meant something like TinyMCE and other wysiwyg's..

I was looking for integrating with codemirror... I *guess* this might be done by getting the cursor position from codemirror instead of caret.js?

I'd like to add a markdown editor to my web app using said scripts.
