### ISSUE TITLE
Condition inside displayTpl

### ISSUE THREAD

**Issue by raphaelbeckmann** [ichord/At.js#569]
Some users have a profile picture, others have not.

How can we insert a condition inside the display template to show, let's say, the initials of users without a profile picture?

The example code below with the ternary operator does not work because `profilePicture` in line 1 is not defined.

```
displayTpl: profilePicture
	? '<li><img src="${profilePicture}"> ${name}</li>',
	: '<li>${initials} ${name}</li>',
```

**Comment by Brandon-Beck** [comment]
@raphaelbeckmann 
I believe headerTpl, displayTpl, and insertTpl can all either be a string or a function. If it is a string, the variables are evaluated just before inserting it.

In your example, your trying to check if profilePicture exists in the current block (function or global), rather than checking if it exists inside the current data object. Also, your ternary operator has commas... for some reason....

For this, you will probably want a function with template literals.

```javascript
data: [
  {name:'Ugly Pig',initials:'UP'}
  ,{profilePicture:'./pretty.png',name:'Pretty Pig',initials:'PP'}
]
,displayTpl: (item) => {
  item.profilePicture
  ? `<li><img src="${item.profilePicture}"> ${item.name}</li>`
  : `<li>${item.initials} ${item.name}</li>`
}
```
You may also wish to consider using the ternary operator in the template literal. eg.
```javascript
displayTpl: (item) => `<li>${ item.profilePicture ? `<img src="${item.profilePicture}">` : item.initials } ${item.name}</li>`
```

Item will be an object that was passed into the data array, with some additional properties (eg. item['atwho-at']).

**Comment by ichord** [comment]
@Brandon-Beck is right, thanks.
